trigger: none

pool: aman-ki-pipeline

variables:
  workdir: '$(System.DefaultWorkingDirectory)\C:\Users\Acer\Downloads\Aman Pipeline\work\aman'
  services: 'Pipeline connection'


steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'


- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(workdir)
    backendServiceArm: $(services)
    backendAzureRmStorageAccountName: 'aman-sa'
    backendAzureRmContainerName: 'sacont'
    backendAzureRmKey: 'tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: $(workdir)
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: $(services)


- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: $(workdir)

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(workdir)
    environmentServiceNameAzureRM: $(services)

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: $(workdir)
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: $(services)